### PR TITLE
Add Information Theory, Parity & Hamming Code, Entropy, Cryptography and Compression sections

### PR DESCRIPTION
**Pull request by oceanjules**
Sections modified:
- Information Theory
- Parity & Hamming Code
- Entropy
- Cryptography
- Compression

And hyperlinks to them are changed to Russian

### CODE REVIEW

**Comment by Ilyushin** [comment]
@PandaJules Can I merge it or you're planning to continue working?

**Comment by oceanjules** [comment]
@Ilyushin I'll probably add some more sections today/tomorrow, so don't merge it for now :)

**Comment by oceanjules** [comment]
@Ilyushin I've stopped working on it a while ago, so I think you should merge (given that somebody else expressed interest on the main repo)

**Comment by Ilyushin** [comment]
Done

**Pull request merged**
